server:
  port: 4433

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Userkwj/microservicecloud-config.git #GitHub上面的git仓库名字