server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway   #对外暴露的微服务名称


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  #eureka集群
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true



zuul:
  prefix: /atguigu #公共前缀
  ignored-services: microservicecloud-dept  #以后不能在使用此路径访问 忽略源访问路径
#  ignored-services: "*"  #批处理 微服务名称都不能访问
  routes: #代理名称
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
    # before
    # http://myzuul.com:9527/microservicecloud-dept/dept/get/1
    # after
    # http://myzuul.com:9527/mydept/dept/get/1



info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
